apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>## listen typed protocol and lisen in port
      @type forward
      port 24223
      bind 0.0.0.0
    </source>

    <match **>
      @type stdout # its to just print the logs in fluentd
    </match>