apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-logging-demo
  labels:
    app: golang-logging-demo
  namespace: logging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-logging-demo
  template:
    metadata:
      labels:
        app: golang-logging-demo
        logging.enabled: "true"
    spec:
      containers:
      - name: golang-logging-demo
        image: fazilnbr/golang-logrus
        ports:
        - containerPort: 8080 # app inside the container listens on port 8080
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"