
apiVersion: v1
kind: Service
metadata:
  name: golang-logging-service
  namespace: logging-app
spec:
  type: ClusterIP
  selector:
    app: golang-logging-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080