apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-filtered
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters, and output
  # =======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        # Plugins_File /fluent-bit/etc/plugins.conf
  
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-stackdriver.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     100MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        # Control the log line length
        Buffer_Chunk_Size       256k
        Buffer_Max_Size         10240k
        # Using the docker mode to deal with multiline messages emitted by docker
        Docker_Mode     On

  replace_info.lua: |
        function replace_sensitive_info(tag, timestamp, record)
          -- Mask social security number
          record["log"] = string.gsub(record["log"], "%d%d%d%-%d%d%-%d%d%d%d", "xxx-xx-xxxx")
          
          -- Mask credit card number
          record["log"] = string.gsub(record["log"], "%d%d%d%d%-%d%d%d%d%-%d%d%d%d%-%d%d%d%d", "xxxx-xxxx-xxxx-xxxx")

          -- Mask password
          record["log"] = string.gsub(record["log"], "\"password\"%s*:%s*\"[^\"]+\"", "\"password\":\"[REDACTED]\"")

          -- Mask bank account numbers (assuming a format of numbers possibly separated by dashes or spaces)
          record["log"] = string.gsub(record["log"], "\"bankAccountNumber\": \"%d[%d%s-]*\"", "\"bankAccountNumber\": \"[REDACTED]\"")

          -- Mask userName
          record["log"] = string.gsub(record["log"], "\"userName\"%s*:%s*\"[^\"]+\"", "\"userName\":\"[REDACTED]\"")

          -- Mask bank account number
          record["log"] = string.gsub(record["log"], "\"bankAccountNumber\"%s*:%s*\"%d+\"", "\"bankAccountNumber\":\"[REDACTED]\"")

          -- Mask email address
          record["log"] = string.gsub(record["log"], "[%w+%.%-_]+@[%w+%.%-_]+%.%a%a+", "user@email.com")

          return 1, timestamp, record
        end

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        # Try to merge the log messages
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        ### sample log scrubbing filters    
    [FILTER]
        Name                lua
        Match               kube.*
        # lua script to redact sensitive data in log messages
        script              replace_info.lua
        call                replace_sensitive_info
        ### end sample log scrubbing

    ## filter with labels
    [FILTER]
        Name   rewrite_tag
        Match  kube.*
        Rule   $kubernetes['labels']['logging.enabled'] ^true$ logs.enabled.$TAG true

    ## filter with namespace
    # [FILTER]
    #     Name                rewrite_tag
    #     Match               kube.*
    #     Rule                $kubernetes['namespace_name'] ^logging-app$ logging.$TAG true


    # it has some issue like the record need to be key value pair so instead of this using the above rewrite tag
    # [FILTER]
    #     Name                record_modifier
    #     Match               kube.*
    #     Record              log ${log:0:256000}


    # [FILTER]
    #     Name                grep
    #     Match               kube.*
    #     # Only log entries from the 'logging' namespace
    #     Regex               kube.namespace_name ^logging$
    #     # Optionally, filter by specific app labels or names
    #     # Regex               kube.container_name ^my-app-container-name$

  output-stackdriver.conf: |
    [OUTPUT]
        Name            opensearch
        Match           logs.enabled.*
        Host            opensearch.logging.svc.cluster.local
        Port            9200
        HTTP_User       admin
        HTTP_Passwd     Z9!kR#4M@pW7eT2x # better to read this from secret or env
        Index           logging-%Y.%m.%d
        Logstash_Format On
        Suppress_Type_Name On
        TLS             On
        TLS.Verify      Off


    ## fluentd output
    # [OUTPUT]
    #     Name          forward
    #     Match         logs.enabled.*
    #     Host          fluentd.logging.svc.cluster.local
    #     Port          24223
    #     Retry_Limit   False
    #     storage.total_limit_size  100M
    [OUTPUT]
        # write the log records that still have the 'kube.*' tags to Cloud Logging
        Name    stackdriver
        Match   kube.*
        # The following fields are necessary. They allow filtering in Cloud Logging
        # based on resource types. Change them accordingly based on your setup.
        resource  k8s_container
        k8s_cluster_name  minikube-cluster
        k8s_cluster_location  local

  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
    